// <auto-generated />
using System;
using AssignmentSubmissionManagementSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssignmentSubmissionManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.AcademicYear", b =>
                {
                    b.Property<long>("AcademicYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("academicyearid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AcademicYearId"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batchid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("yearname");

                    b.Property<int>("YearOrder")
                        .HasColumnType("integer")
                        .HasColumnName("yearorder");

                    b.HasKey("AcademicYearId")
                        .HasName("academicyears_pkey");

                    b.HasAlternateKey("InstitutionId", "AcademicYearId")
                        .HasName("uq_academicyears_institution_academicyear");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_academicyears_batchid");

                    b.HasIndex("InstitutionId", "BatchId", "YearName")
                        .IsUnique()
                        .HasDatabaseName("uq_academicyears_institution_batch_yearname");

                    b.HasIndex("InstitutionId", "BatchId", "YearOrder")
                        .IsUnique()
                        .HasDatabaseName("uq_academicyears_institution_batch_yearorder");

                    b.ToTable("academicyears", null, t =>
                        {
                            t.HasCheckConstraint("ck_academicyears_name", "length(trim(yearname)) > 0");

                            t.HasCheckConstraint("ck_academicyears_yearorder", "yearorder > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Batch", b =>
                {
                    b.Property<long>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("batchid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BatchId"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("batchcode");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("batchname");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("courseid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnName("endyear");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("startyear");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("BatchId")
                        .HasName("batches_pkey");

                    b.HasAlternateKey("InstitutionId", "BatchId")
                        .HasName("uq_batches_institution_batch");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_batches_courseid");

                    b.HasIndex("InstitutionId", "BatchCode")
                        .IsUnique()
                        .HasDatabaseName("uq_batches_institution_code");

                    b.HasIndex("InstitutionId", "CourseId");

                    b.ToTable("batches", null, t =>
                        {
                            t.HasCheckConstraint("ck_batches_code", "length(trim(batchcode)) > 0");

                            t.HasCheckConstraint("ck_batches_name", "length(trim(batchname)) > 0");

                            t.HasCheckConstraint("ck_batches_yearrange", "endyear IS NULL OR endyear >= startyear");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("courseid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("coursecode");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("coursename");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("departmentid");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("CourseId")
                        .HasName("courses_pkey");

                    b.HasAlternateKey("InstitutionId", "CourseId")
                        .HasName("uq_courses_institution_course");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_courses_departmentid");

                    b.HasIndex("InstitutionId", "CourseCode")
                        .IsUnique()
                        .HasDatabaseName("uq_courses_institution_code");

                    b.HasIndex("InstitutionId", "DepartmentId");

                    b.ToTable("courses", null, t =>
                        {
                            t.HasCheckConstraint("ck_courses_code", "length(trim(coursecode)) > 0");

                            t.HasCheckConstraint("ck_courses_name", "length(trim(coursename)) > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.CourseSubject", b =>
                {
                    b.Property<long>("CourseSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("coursesubjectid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CourseSubjectId"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("courseid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("subjectid");

                    b.HasKey("CourseSubjectId")
                        .HasName("coursesubjects_pkey");

                    b.HasAlternateKey("InstitutionId", "CourseSubjectId")
                        .HasName("uq_coursesubjects_institution_coursesubject");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_coursesubjects_subjectid");

                    b.HasIndex("InstitutionId", "SubjectId");

                    b.HasIndex("InstitutionId", "CourseId", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("uq_coursesubjects_institution_course_subject");

                    b.ToTable("coursesubjects", (string)null);
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Department", b =>
                {
                    b.Property<long>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("departmentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("departmentcode");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departmentname");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("DepartmentId")
                        .HasName("departments_pkey");

                    b.HasAlternateKey("InstitutionId", "DepartmentId")
                        .HasName("uq_departments_institution_department");

                    b.HasIndex("InstitutionId", "DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("uq_departments_institution_code");

                    b.ToTable("departments", null, t =>
                        {
                            t.HasCheckConstraint("ck_departments_code", "length(trim(departmentcode)) > 0");

                            t.HasCheckConstraint("ck_departments_name", "length(trim(departmentname)) > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.StudentEnrollment", b =>
                {
                    b.Property<long>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("enrollmentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EnrollmentId"));

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("bigint")
                        .HasColumnName("academicyearid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("EnrollmentDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollmentdate");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rollnumber");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("studentid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("EnrollmentId")
                        .HasName("studentenrollments_pkey");

                    b.HasIndex("AcademicYearId")
                        .HasDatabaseName("ix_studentenrollments_academicyearid");

                    b.HasIndex("InstitutionId", "EnrollmentId")
                        .IsUnique()
                        .HasDatabaseName("uq_studentenrollments_institution_enrollment");

                    b.HasIndex("InstitutionId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("uq_studentenrollments_onlyoneactive")
                        .HasFilter("isactive = TRUE");

                    b.HasIndex("InstitutionId", "AcademicYearId", "RollNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_studentenrollments_institution_academicyear_roll");

                    b.HasIndex("InstitutionId", "StudentId", "AcademicYearId")
                        .IsUnique()
                        .HasDatabaseName("uq_studentenrollments_institution_student_academicyear");

                    b.ToTable("studentenrollments", null, t =>
                        {
                            t.HasCheckConstraint("ck_studentenrollments_roll", "length(trim(rollnumber)) > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.StudentProfile", b =>
                {
                    b.Property<long>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("studentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StudentId"));

                    b.Property<DateOnly?>("AdmissionDate")
                        .HasColumnType("date")
                        .HasColumnName("admissiondate");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("studentcode");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userid");

                    b.HasKey("StudentId")
                        .HasName("studentprofiles_pkey");

                    b.HasAlternateKey("InstitutionId", "StudentId")
                        .HasName("uq_studentprofiles_institution_student");

                    b.HasIndex("InstitutionId", "StudentCode")
                        .IsUnique()
                        .HasDatabaseName("uq_studentprofiles_institution_studentcode");

                    b.HasIndex("InstitutionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_studentprofiles_institution_user");

                    b.ToTable("studentprofiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_studentprofiles_studentcode", "length(trim(studentcode)) > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Subject", b =>
                {
                    b.Property<long>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("subjectid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SubjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("subjectcode");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subjectname");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("SubjectId")
                        .HasName("subjects_pkey");

                    b.HasAlternateKey("InstitutionId", "SubjectId")
                        .HasName("uq_subjects_institution_subject");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_subjects_institutionid");

                    b.HasIndex("InstitutionId", "SubjectCode")
                        .IsUnique()
                        .HasDatabaseName("uq_subjects_institution_code");

                    b.ToTable("subjects", null, t =>
                        {
                            t.HasCheckConstraint("ck_subjects_code", "length(trim(subjectcode)) > 0");

                            t.HasCheckConstraint("ck_subjects_name", "length(trim(subjectname)) > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.TeacherProfile", b =>
                {
                    b.Property<long>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("teacherid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TeacherId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("departmentid");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employeecode");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("joiningdate");

                    b.Property<string>("Qualification")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("qualification");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userid");

                    b.HasKey("TeacherId")
                        .HasName("teacherprofiles_pkey");

                    b.HasAlternateKey("InstitutionId", "TeacherId")
                        .HasName("uq_teacherprofiles_institution_teacher");

                    b.HasIndex("InstitutionId", "DepartmentId");

                    b.HasIndex("InstitutionId", "EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("uq_teacherprofiles_institution_employeecode");

                    b.HasIndex("InstitutionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_teacherprofiles_institution_user");

                    b.ToTable("teacherprofiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_teacherprofiles_employeecode", "length(trim(employeecode)) > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.TeacherSubject", b =>
                {
                    b.Property<long>("TeacherSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("teachersubjectid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TeacherSubjectId"));

                    b.Property<long>("CourseSubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("coursesubjectid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacherid");

                    b.HasKey("TeacherSubjectId")
                        .HasName("teachersubjects_pkey");

                    b.HasAlternateKey("InstitutionId", "TeacherId", "CourseSubjectId")
                        .HasName("uq_teachersubjects_institution_teacher_coursesubject");

                    b.HasIndex("CourseSubjectId")
                        .HasDatabaseName("ix_teachersubjects_coursesubjectid");

                    b.HasIndex("InstitutionId", "CourseSubjectId");

                    b.HasIndex("InstitutionId", "TeacherSubjectId")
                        .IsUnique()
                        .HasDatabaseName("uq_teachersubjects_institution_teachersubject");

                    b.ToTable("teachersubjects", (string)null);
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Assessment", b =>
                {
                    b.Property<long>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("assessmentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AssessmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<decimal>("FinalMarks")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("finalmarks");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<decimal>("MarksObtained")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("marksobtained");

                    b.Property<int>("PenaltyPercentageApplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("penaltypercentageapplied");

                    b.Property<long?>("PolicyId")
                        .HasColumnType("bigint")
                        .HasColumnName("policyid");

                    b.Property<DateTime>("ReviewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reviewedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submissionid");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacherid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("AssessmentId")
                        .HasName("assessments_pkey");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_assessments_teacherid");

                    b.HasIndex("InstitutionId", "PolicyId");

                    b.HasIndex("InstitutionId", "SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("uq_assessments_institution_submission");

                    b.HasIndex("InstitutionId", "TeacherId");

                    b.ToTable("assessments", null, t =>
                        {
                            t.HasCheckConstraint("ck_assessments_marks", "marksobtained >= 0\r\nAND finalmarks >= 0\r\nAND finalmarks <= marksobtained");

                            t.HasCheckConstraint("ck_assessments_penaltypercentage", "penaltypercentageapplied BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_assessments_policyusage", "(policyid IS NULL AND penaltypercentageapplied = 0)\r\nOR\r\n(policyid IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Assignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("assignmentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AssignmentId"));

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("bigint")
                        .HasColumnName("academicyearid");

                    b.Property<bool>("AllowLateSubmission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allowlatesubmission");

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("assignmentstatus");

                    b.Property<long>("CourseSubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("coursesubjectid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("duedate");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<DateTime?>("LateSubmissionDeadline")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("latesubmissiondeadline");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacherid");

                    b.Property<long>("TeacherSubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<decimal>("TotalMarks")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("totalmarks");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("AssignmentId")
                        .HasName("assignments_pkey");

                    b.HasAlternateKey("InstitutionId", "AssignmentId")
                        .HasName("uq_assignments_institution_assignment");

                    b.HasIndex("AcademicYearId")
                        .HasDatabaseName("ix_assignments_academicyearid");

                    b.HasIndex("CourseSubjectId")
                        .HasDatabaseName("ix_assignments_coursesubjectid");

                    b.HasIndex("InstitutionId", "AcademicYearId");

                    b.HasIndex("InstitutionId", "CourseSubjectId");

                    b.HasIndex("InstitutionId", "TeacherId", "CourseSubjectId");

                    b.ToTable("assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_assignments_latesubmission", "(allowlatesubmission = FALSE AND latesubmissiondeadline IS NULL)\r\nOR\r\n(allowlatesubmission = TRUE\r\n AND latesubmissiondeadline IS NOT NULL\r\n AND latesubmissiondeadline > duedate)");

                            t.HasCheckConstraint("ck_assignments_status", "assignmentstatus IN ('Draft', 'Published', 'Closed', 'Archived')");

                            t.HasCheckConstraint("ck_assignments_title", "length(trim(title)) > 0");

                            t.HasCheckConstraint("ck_assignments_totalmarks", "totalmarks > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.AssignmentAttachment", b =>
                {
                    b.Property<long>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("attachmentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AttachmentId"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignmentid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filename");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("filepath");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("filesize");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("filetype");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.HasKey("AttachmentId")
                        .HasName("assignmentattachments_pkey");

                    b.HasIndex("InstitutionId", "AssignmentId");

                    b.ToTable("assignmentattachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_assignmentattachments_filename", "length(trim(filename)) > 0");

                            t.HasCheckConstraint("ck_assignmentattachments_filepath", "length(trim(filepath)) > 0");

                            t.HasCheckConstraint("ck_assignmentattachments_filesize", "filesize IS NULL OR filesize >= 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.LateSubmissionPolicy", b =>
                {
                    b.Property<long>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("policyid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PolicyId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<int>("PenaltyPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(25)
                        .HasColumnName("penaltypercentage");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("policyname");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("PolicyId")
                        .HasName("latesubmissionpolicies_pkey");

                    b.HasAlternateKey("InstitutionId", "PolicyId")
                        .HasName("uq_latesubmissionpolicies_institution_policy");

                    b.HasIndex("InstitutionId")
                        .IsUnique()
                        .HasDatabaseName("uq_latesubmissionpolicies_onlyoneactive")
                        .HasFilter("isactive = TRUE");

                    b.HasIndex("InstitutionId", "PolicyName")
                        .IsUnique()
                        .HasDatabaseName("uq_latesubmissionpolicies_institution_name");

                    b.ToTable("latesubmissionpolicies", null, t =>
                        {
                            t.HasCheckConstraint("ck_latesubmissionpolicies_name", "length(trim(policyname)) > 0");

                            t.HasCheckConstraint("ck_latesubmissionpolicies_penalty", "penaltypercentage BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.ResubmissionApproval", b =>
                {
                    b.Property<long>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("approvalid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ApprovalId"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("approvalstatus");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isused");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("requestid");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reviewedat");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacherid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("usedat");

                    b.HasKey("ApprovalId")
                        .HasName("resubmissionapprovals_pkey");

                    b.HasIndex("InstitutionId", "RequestId")
                        .IsUnique()
                        .HasDatabaseName("uq_resubmissionapprovals_institution_request");

                    b.HasIndex("InstitutionId", "TeacherId");

                    b.ToTable("resubmissionapprovals", null, t =>
                        {
                            t.HasCheckConstraint("ck_resubmissionapprovals_reviewedat", "(approvalstatus = 'Pending' AND reviewedat IS NULL)\r\nOR\r\n(approvalstatus IN ('Approved', 'Rejected')\r\n AND reviewedat IS NOT NULL)");

                            t.HasCheckConstraint("ck_resubmissionapprovals_status", "approvalstatus IN ('Pending', 'Approved', 'Rejected')");

                            t.HasCheckConstraint("ck_resubmissionapprovals_usage", "(isused = FALSE AND usedat IS NULL)\r\nOR\r\n(isused = TRUE\r\n AND approvalstatus = 'Approved'\r\n AND usedat IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.ResubmissionRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("requestid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submissionid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("RequestId")
                        .HasName("resubmissionrequests_pkey");

                    b.HasAlternateKey("InstitutionId", "RequestId")
                        .HasName("uq_resubmissionrequests_institution_request");

                    b.HasIndex("InstitutionId", "SubmissionId");

                    b.ToTable("resubmissionrequests", null, t =>
                        {
                            t.HasCheckConstraint("ck_resubmissionrequests_reason", "length(trim(reason)) > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Submission", b =>
                {
                    b.Property<long>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("submissionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SubmissionId"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignmentid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsLateSubmission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("islatesubmission");

                    b.Property<bool>("IsLatestSubmission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("islatestsubmission");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("studentid");

                    b.Property<string>("SubmissionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Submitted")
                        .HasColumnName("submissionstatus");

                    b.Property<string>("SubmissionText")
                        .HasColumnType("text")
                        .HasColumnName("submissiontext");

                    b.Property<int>("SubmissionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("submissionversion");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("submittedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("SubmissionId")
                        .HasName("submissions_pkey");

                    b.HasAlternateKey("InstitutionId", "SubmissionId")
                        .HasName("uq_submissions_institution_submission");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_submissions_assignmentid");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_submissions_studentid");

                    b.HasIndex("InstitutionId", "AssignmentId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("uq_submissions_onlyonelatest")
                        .HasFilter("islatestsubmission = TRUE");

                    b.HasIndex("InstitutionId", "AssignmentId", "StudentId", "SubmissionVersion")
                        .IsUnique()
                        .HasDatabaseName("uq_submissions_institution_assignment_student_version");

                    b.ToTable("submissions", null, t =>
                        {
                            t.HasCheckConstraint("ck_submissions_content", "submissiontext IS NULL OR length(trim(submissiontext)) > 0");

                            t.HasCheckConstraint("ck_submissions_version", "submissionversion > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.SubmissionAttachment", b =>
                {
                    b.Property<long>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("attachmentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AttachmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filename");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("filepath");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("filesize");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("filetype");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submissionid");

                    b.HasKey("AttachmentId")
                        .HasName("submissionattachments_pkey");

                    b.HasIndex("SubmissionId");

                    b.ToTable("submissionattachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_submissionattachments_filename", "length(trim(filename)) > 0");

                            t.HasCheckConstraint("ck_submissionattachments_filepath", "length(trim(filepath)) > 0");

                            t.HasCheckConstraint("ck_submissionattachments_filesize", "filesize IS NULL OR filesize >= 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Core.Institution", b =>
                {
                    b.Property<long>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InstitutionId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("InstitutionCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("institutioncode");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("institutionname");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phonenumber");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("InstitutionId")
                        .HasName("institutions_pkey");

                    b.HasIndex("InstitutionCode")
                        .IsUnique()
                        .HasDatabaseName("institutions_institutioncode_key");

                    b.ToTable("institutions", null, t =>
                        {
                            t.HasCheckConstraint("ck_institutions_code", "length(trim(institutioncode)) > 0");

                            t.HasCheckConstraint("ck_institutions_name", "length(trim(institutionname)) > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Core.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("roleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rolename");

                    b.HasKey("RoleId")
                        .HasName("roles_pkey");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("roles_rolename_key");

                    b.ToTable("roles", null, t =>
                        {
                            t.HasCheckConstraint("ck_roles_name", "length(trim(rolename)) > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Core.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fullname");

                    b.Property<long?>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phonenumber");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("roleid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasAlternateKey("InstitutionId", "UserId")
                        .HasName("uq_users_institution_user");

                    b.HasIndex("RoleId");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email", "length(trim(email)) > 0");

                            t.HasCheckConstraint("ck_users_fullname", "length(trim(fullname)) > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.System.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("auditlogid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entityid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entityname");

                    b.Property<long?>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("newvalues");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("oldvalues");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userid");

                    b.HasKey("AuditLogId")
                        .HasName("auditlogs_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex("InstitutionId", "UserId", "CreatedAt")
                        .HasDatabaseName("ix_auditlogs_institution_user_createdat");

                    b.ToTable("auditlogs", null, t =>
                        {
                            t.HasCheckConstraint("ck_auditlogs_action", "action IN\r\n(\r\n    'CREATE',\r\n    'UPDATE',\r\n    'DELETE',\r\n    'APPROVE',\r\n    'REJECT',\r\n    'SUBMIT',\r\n    'REVIEW',\r\n    'LOGIN',\r\n    'LOGOUT',\r\n    'PUBLISH'\r\n)");

                            t.HasCheckConstraint("ck_auditlogs_entityid", "entityid > 0");

                            t.HasCheckConstraint("ck_auditlogs_entityname", "length(trim(entityname)) > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.System.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("notificationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificationId"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("InApp")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("InstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("institutionid");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isread");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("notificationtype");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("readat");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("referenceid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userid");

                    b.HasKey("NotificationId")
                        .HasName("notifications_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex("InstitutionId", "UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_institution_user_isread");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_notifications_channel", "channel IN ('InApp', 'Email', 'SMS', 'Push')");

                            t.HasCheckConstraint("ck_notifications_message", "length(trim(message)) > 0");

                            t.HasCheckConstraint("ck_notifications_readstate", "(isread = FALSE AND readat IS NULL)\r\nOR\r\n(isread = TRUE AND readat IS NOT NULL)");

                            t.HasCheckConstraint("ck_notifications_title", "length(trim(title)) > 0");
                        });
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.AcademicYear", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "BatchId")
                        .HasPrincipalKey("InstitutionId", "BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_academicyears_institutionbatches");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Batch", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Course", "Course")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "CourseId")
                        .HasPrincipalKey("InstitutionId", "CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batches_institutioncourses");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Course", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Department", "Department")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "DepartmentId")
                        .HasPrincipalKey("InstitutionId", "DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_courses_institutiondepartments");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.CourseSubject", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Course", "Course")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "CourseId")
                        .HasPrincipalKey("InstitutionId", "CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coursesubjects_institutioncourses");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "SubjectId")
                        .HasPrincipalKey("InstitutionId", "SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coursesubjects_institutionsubjects");

                    b.Navigation("Course");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Department", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Core.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_departments_institutions");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.StudentEnrollment", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "AcademicYearId")
                        .HasPrincipalKey("InstitutionId", "AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_studentenrollments_institutionacademicyears");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.StudentProfile", "Student")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "StudentId")
                        .HasPrincipalKey("InstitutionId", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_studentenrollments_institutionstudents");

                    b.Navigation("AcademicYear");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.StudentProfile", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Core.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_studentprofiles_institutions");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Core.User", "User")
                        .WithOne()
                        .HasForeignKey("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.StudentProfile", "InstitutionId", "UserId")
                        .HasPrincipalKey("AssignmentSubmissionManagementSystem.Domain.Entities.Core.User", "InstitutionId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_studentprofiles_institutionusers");

                    b.Navigation("Institution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Subject", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Core.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subjects_institutions");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.TeacherProfile", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Core.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.Department", "Department")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "DepartmentId")
                        .HasPrincipalKey("InstitutionId", "DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacherprofiles_institutiondepartments");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "UserId")
                        .HasPrincipalKey("InstitutionId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacherprofiles_institutionusers");

                    b.Navigation("Department");

                    b.Navigation("Institution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.TeacherSubject", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.CourseSubject", "CourseSubject")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "CourseSubjectId")
                        .HasPrincipalKey("InstitutionId", "CourseSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teachersubjects_institutioncoursesubjects");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.TeacherProfile", "Teacher")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "TeacherId")
                        .HasPrincipalKey("InstitutionId", "TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teachersubjects_institutionteachers");

                    b.Navigation("CourseSubject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Assessment", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.LateSubmissionPolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "PolicyId")
                        .HasPrincipalKey("InstitutionId", "PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_assessments_institutionpolicies");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Submission", "Submission")
                        .WithOne()
                        .HasForeignKey("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Assessment", "InstitutionId", "SubmissionId")
                        .HasPrincipalKey("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Submission", "InstitutionId", "SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assessments_institutionsubmissions");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.TeacherProfile", "Teacher")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "TeacherId")
                        .HasPrincipalKey("InstitutionId", "TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assessments_institutionteachers");

                    b.Navigation("Policy");

                    b.Navigation("Submission");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Assignment", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "AcademicYearId")
                        .HasPrincipalKey("InstitutionId", "AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_institutionacademicyears");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.CourseSubject", "CourseSubject")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "CourseSubjectId")
                        .HasPrincipalKey("InstitutionId", "CourseSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_institutioncoursesubjects");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.TeacherProfile", "Teacher")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "TeacherId")
                        .HasPrincipalKey("InstitutionId", "TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_institutionteachers");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.TeacherSubject", "TeacherSubject")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "TeacherId", "CourseSubjectId")
                        .HasPrincipalKey("InstitutionId", "TeacherId", "CourseSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_institutionteachersubjects");

                    b.Navigation("AcademicYear");

                    b.Navigation("CourseSubject");

                    b.Navigation("Teacher");

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.AssignmentAttachment", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "AssignmentId")
                        .HasPrincipalKey("InstitutionId", "AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignmentattachments_institutionassignments");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.LateSubmissionPolicy", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Core.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_latesubmissionpolicies_institutions");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.ResubmissionApproval", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.ResubmissionRequest", "Request")
                        .WithOne()
                        .HasForeignKey("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.ResubmissionApproval", "InstitutionId", "RequestId")
                        .HasPrincipalKey("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.ResubmissionRequest", "InstitutionId", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resubmissionapprovals_institutionrequests");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.TeacherProfile", "Teacher")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "TeacherId")
                        .HasPrincipalKey("InstitutionId", "TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resubmissionapprovals_institutionteachers");

                    b.Navigation("Request");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.ResubmissionRequest", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("InstitutionId", "SubmissionId")
                        .HasPrincipalKey("InstitutionId", "SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resubmissionrequests_institutionsubmissions");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Submission", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_assignments");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Academic.StudentProfile", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_students");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.SubmissionAttachment", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Submission", "Submission")
                        .WithMany("SubmissionAttachments")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissionattachments_submissions");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.Core.User", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Core.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_institutions");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Core.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles");

                    b.Navigation("Institution");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.System.AuditLog", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Core.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auditlogs_institutions");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auditlogs_users");

                    b.Navigation("Institution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.System.Notification", b =>
                {
                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Core.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notifications_institutions");

                    b.HasOne("AssignmentSubmissionManagementSystem.Domain.Entities.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users");

                    b.Navigation("Institution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AssignmentSubmissionManagementSystem.Domain.Entities.AssignmentManagement.Submission", b =>
                {
                    b.Navigation("SubmissionAttachments");
                });
#pragma warning restore 612, 618
        }
    }
}
